-- Tabla para los reglamentos (similar a doc_normativos, con soporte para subítems/modificaciones)
CREATE TABLE reglamentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    seccion VARCHAR(100) NOT NULL,               -- 'REGLAMENTOS', 'EJERCICIO PRE PROFESIONAL', 'INTERNADO', 'GRADOS Y TÍTULOS', 'POSGRADO', 'SEGUNDAS ESPECIALIDADES', 'DEFENSORIA UNIVERSITARIA'
    titulo TEXT NOT NULL,                        -- Título completo del reglamento
    resolucion VARCHAR(255) DEFAULT NULL,        -- Texto de resolución (puede ser NULL)
    es_subitem TINYINT(1) DEFAULT 0,             -- 1 si es modificación/subitem, 0 si principal
    enlace TEXT NOT NULL                         -- Enlace completo al PDF
);

-- Inserción de datos manteniendo exactamente el orden y estructura de la página/imagen

-- === REGLAMENTOS ===
INSERT INTO reglamentos (seccion, titulo, resolucion, es_subitem, enlace) VALUES
('REGLAMENTOS', 'REGLAMENTO INTERNO DE SEGURIDAD Y SALUD EN EL TRABAJO 2026-2028 DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°573-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/reglamentos/2025/R_CU-573-2025-UAC-seguridad-salud-trabajo.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE LA BIBLIOTECA UNIVERSITARIA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°457-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-457-2025-UAC-reglamento-biblioteca-universitaria.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE MATRÍCULA ANTICIPADA PARA INGRESANTES ADMITIDOSPARA TODAS LAS MODALIDADES DE PREGRADO, (EXCEPTO LA MODALIDAD ORDINARIA) DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°379-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-379-2025-UAC-reglamento-matricula-anticipada.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE CERTIFICACIÓN INTERMEDIA DE LA ESCUELA PROFESIONAL DE INGENIERÍA CIVIL DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°297-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-297-2025-UAC-reglamento-certificacion-intermedia-civil.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE CERTIFICACIÓN INTERMEDIA DE LA ESCUELA PROFESIONAL DE INGENIERÍA INDUSTRIAL DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°296-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-296-2025-UAC-reglamento-certificacion-intermedia-industrial.pdf'),
('REGLAMENTOS', 'REGLAMENTO ESPECÍFICO DE CERTIFICACIÓN INTERMEDIA DE LA ESCUELA PROFESIONAL DE ARQUITECTURA LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°295-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-295-2025-UAC-reglamento-certificacion-intermedia-arquitectura.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE MOVILIDAD DOCENTE DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°225-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-225-2025-UAC-reglamento-movilidad-docente.pdf'),
('REGLAMENTOS', 'REGLAMENTO ESPECÍFICO DE ELECCIONES UNIVERSALES PARA RECTOR, VICERRECTORES Y DECANOS DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°173-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-173-2025-UAC-reglamento-especifico-rector-vicerrectores-decanos.pdf'),
('REGLAMENTOS', 'REGLAMENTO GENERAL DE ELECCIONES UNIVERSITARIAS DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°172-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-172-2025-UAC-reglamento-general-elecciones.pdf'),
('REGLAMENTOS', 'REGLAMENTO INTERNO DEL TRABAJO DEL PERSONAL ADMINISTRATIVO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 001-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-001-2025-UAC-reglamento-interno-personal-administrativo.pdf'),
('REGLAMENTOS', 'REGLAMENTO INTERNO DEL CENTRO DE IDIOMAS DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 662-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-662-2024-UAC-reglamento-centro-idiomas.pdf'),
('REGLAMENTOS', 'Modifican Parcialmente la resolución N° 662-CU-2024-UAC, que aprueba el reglamento interno del Centro de Idiomas de la Universidad Andina del Cusco', 'Res. N° 184-2025/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R-CU-184-2025-UAC-modificacion-Res662CU2024.pdf'),
('REGLAMENTOS', 'Modifican en parte la resolución N° 662 en el extremo que corresponde al artículo 38', 'Res. N° 068-2025/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R-CU-068-2025-UAC-modificacion-Res662CU2024.pdf'),
('REGLAMENTOS', 'APRUEBAN EL REGLAMENTO DE CERTIFICACIÓN INTERMEDIA DE LA ESCUELA PROFESIONAL DE INGENIERÍA AMBIENTAL DE LA FACULTAD DE INGENIERÍA Y ARQUITECTURA', 'Res. N°586-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-586-2024-UAC-reglamento-certificacion-intermedia-ambiental.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE PAGO POR SERVICIOS EDUCATIVOS PARA ESTUDIANTES CON TARIFA A PARTIR DEL AÑO 2025', 'Res. N°583-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-583-2024-UAC-reglamento-pago-servicios-educativos-2025.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL CENTRO PRE UNIVERSITARIO DE CONSOLIDACIÓN DEL PERFIL DEL INGRESANTE (CPCPI) DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°522-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-522-2024-UAC-aprueban-reglamento-cpcpi.pdf'),
('REGLAMENTOS', 'REGLAMENTO GENERAL DE ADMISIÓN DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°521-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-521-2024-UAC-reglamento-general-admision-uac.pdf'),
('REGLAMENTOS', 'Modifican parcialmente la resolución N° 521-CU-2024-UAC, de fecha 15 de octubre de 2024', 'Res. N° 591-2025/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/reglamentos/2025/R-CU-591-2025-UAC-modificacion-Res521CU2024.pdf'),
('REGLAMENTOS', 'Modifican parcialmente la resolución N° 521-CU-2024-UAC, de fecha 15 de octubre de 2024', 'Res. N° 271-2025/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R-CU-271-2025-UAC-modificacion-Res521CU2024.pdf'),
('REGLAMENTOS', 'Modifican parcialmente la resolución N° 521 en lo que respecta a la modalidad de ingreso para los exonerados', 'Res. N° 565-2024/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R-CU-565-2024-UAC-modificacion-Res521CU2024.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL DEPORTE GENERAL, DE ALTA COMPETENCIA Y HABILIDADES ESPECIALES DE LA DIRECCIÓN DE PROMOCIÓN DEL DEPORTE DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 022-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-022-2024-UAC-deporte-general-dipd.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL COMITÉ INSTITUCIONAL DE ÉTICA EN INVESTIGACIÓN DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 474-2023/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-474-2023-UAC-comite-etica-investigacion.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE MÉRITOS ACADÉMICOS DE ESTUDIANTES Y EGRESADOS DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°451-2023/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-451-2023-UAC-reglamento-meritos-academicos.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE PUBLICACIONES DE LA UNIVERSIDAD ANDINA DEL CUSCO Y ANEXO.', 'Res. N°448-2023/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-448-2023-UAC-reglamento-publicaciones-uac.pdf'),
('REGLAMENTOS', 'REGLAMENTO PARA CONVOCATORIA, EVALUACIÓN, CONTRATO Y ESCALA REMUNERATIVA DE DOCENTES INVESTIGADORES RENACYT DEL INSTITUTO CIENTÍFICO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°728-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-728-2022-UAC-reglamento-docentes-renacyt.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE HOMOLOGACIONES Y CONVALIDACIONES DE PREGRADO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°470-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-470-2022-UAC-homologacion-convalidacion-pregrado.pdf'),
('REGLAMENTOS', 'REGLAMENTO GENERAL DEL SISTEMA DE BECAS DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°044-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-044-2022-UAC-reglamento-becas.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE MATRÍCULAS DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 588-2021/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_CU-588-2021-UAC-reglamento-matriculas.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE PAGO POR SERVICIOS EDUCATIVOS PARA ESTUDIANTES DE PREGRADO, SEGUNDAS ESPECIALIDADES Y POSGRADO Y SUS ANEXOS', 'Res. N°552-2021/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_CU-552-2021-UAC-reglamento-pago-servicios-educativos.pdf'),
('REGLAMENTOS', 'Modifican los artículos 36 y 7 del reglamento de pago por servicios educativos', 'Res. N° 401-2022/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-401-2022-UAC-modificacion-pago-servicios-120822.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE ASCENSOS DEL PERSONAL DOCENTE DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 515-2021/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_CU-515-2021-UAC-reglamento-ascenso-docente.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE CAMBIO DE RÉGIMEN DEL PERSONAL DOCENTE DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 516-2021/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_CU-516-2021-UAC-reglamento-regimen-docente.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE MOVILIDAD ESTUDIANTIL VIRTUAL DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°141-2021/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_CU-141-2021-UAC-movilidad-estudiantil-virtual.pdf'),
('REGLAMENTOS', 'Deja en suspenso la aplicación de la resolución N° 141-CU-2021-UAC mediante la cual se aprueba el reglamento de movilidad estudiantil virtual de la Universidad Andina del Cusco', 'Res. N° 331-2021/R-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_R-331-2021-UAC-suspenden-aplicacion-cu141-2021.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL TRIBUNAL DE HONOR DE LA UNIVERSIDAD ANDINA DEL CUSCO VIRTUALIZADO', 'Res. N°339-2020/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2020/R_CU-339-2020-UAC-reglamento-tribunal-honor.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE INGRESO, ESTUDIOS Y GRADOS ACADÉMICOS DE LA ESCUELA DE POSGRADO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°415-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-415-2022-UAC-reglamento-epg.pdf'),
('REGLAMENTOS', 'Modificar en parte la resolución N°415-CU-2022-UAC de fecha 15 de agosto de 2022, por consiguiente, aprobar la modificación del Reglamento de ingreso, estudios y grados académicos de la EPG', 'Res. N° 441-2023/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-441-2023-UAC-modifican-Res4152022.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE EVALUACIÓN DE LOS ESTUDIANTES DE PREGRADO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°261-2019/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2019/R_CU-261-2019-UAC-evaluacion-pregrado.pdf'),
('REGLAMENTOS', 'Modifican artículo 27° del reglamento 261-2019/CU-UAC', 'Res. N° 643-2021/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_CU-643-2021-UAC-modificacion-261-2019.pdf'),
('REGLAMENTOS', 'Modifican artículo 21° del reglamento 261-2019/CU-UAC', 'Res. N° 388-2020/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2020/R_CU-388-2020-UAC-modificacion-261-2019.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE RATIFICACIÓN DE LOS DOCENTES DE LA UNIVERSIDAD ANDINA DEL CUSCO.', 'Res. N°095-2019/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2019/R_CU-095-2019-UAC-reglamento-ratificacion-docentes.pdf'),
('REGLAMENTOS', 'Modifican artículo 16° del Reglamento de Ratificación de los Docentes', 'Res. N° 172-2019/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2019/R_CU-172-2019-UAC-modificacion-reglamento-0952019.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE FORMACIÓN DEL COMITÉ DE DEFENSA CIVIL Y BRIGADAS DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°574-2018/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-574-2018-UAC-comite-defensa-civil.pdf'),
('REGLAMENTOS', 'REGLAMENTO GENERAL DE INGRESO COMO DOCENTE ORDINARIO A LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 458-2018/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-458-2018-UAC-reglamento-docente-ordinario.pdf'),
('REGLAMENTOS', 'Rectifican por error material el numeral 2 del artículo 15° del Reglamento 458-2018-CU-UAC.', 'Res. N°513-2018/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-513-2018-UAC-rectificacion-458CU2018.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL CENTRO DE FORMACIÓN EN TECNOLOGÍAS DE INFORMACIÓN (CENFOTI) DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 230-2018/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-230-2018-UAC-reglamento-cenfoti.pdf'),
('REGLAMENTOS', 'Suprimen los numerales 3 y 4 del artículo 19 de la resolución N° 230-CU-2018-UAC', 'Res. N°245-2019/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2019/R_CU-245-2019-UAC-suprimen-art-230CU2018.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE CREACIÓN Y FUNCIONAMIENTO DE LA INCUBADORA DE EMPRESAS DE LA UNIVERSIDAD ANDINA DEL CUSCO, INCUBA ANDINA LAB', 'Res. N° 159-2018/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-159-2018-UAC-reglamento-incuba-andinalab.pdf'),
('REGLAMENTOS', 'Rectifican los artículos 8, 10, 13, 19, 24, 33, 35, 51 y 56 del Reglamento 159-2018-CU-UAC.', 'Res. N°428-2018/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-428-2018-UAC-rectificacion-art-159CU2018.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL REGISTRO DE TRABAJOS DE INVESTIGACIÓN, REPOSITORIO DIGITAL INSTITUCIONALY PLAGIO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 114-2018/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-114-2018-UAC-reglamento-trabajos-investigacion-repositorio-plagio.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE PROPIEDAD INTELECTUAL DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 113-2018/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-113-2018-UAC-reglamento-propiedad-intelectual.pdf'),
('REGLAMENTOS', 'REGLAMENTO MARCO PARA OTORGAR CERTIFICACIÓN DE FORMACIÓN INTERMEDIA EN LAS ESCUELAS PROFESIONALES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°485-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-485-2017-UAC-reglamento-certificacion-intermedia.pdf'),
('REGLAMENTOS', 'Suprimen el artículo 10 del reglamento marco para otorgar certificación de formación intermedia en las escuelas profesionales de la Universidad Andina del Cusco', 'Res. N°572-2024/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-572-2024-UAC-modificacion-reglamento-485CU2017.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE CERTIFICACIÓN DE FORMACIÓN INTERMEDIA CON MENCIÓN EN ASISTENTE EN FINANZAS CORPORATIVAS DE LA ESCUELA PROFESIONAL DE FINANZAS DE LA UAC', 'Res. N°635-2019/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2019/R_CU-635-2019-UAC-certificacion-intermedia-finanzas.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE FINANCIAMIENTO O COFINANCIAMIENTO DE PROYECTOS DE INVESTIGACIÓN DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°463-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-463-2017-UAC-reglamento-financiamiento-investigacion.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE LA CLÍNICA ESTOMATOLÓGICA “LUIS VALLEJOS SANTONI”', 'Res. N°449-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-449-2017-UAC-reglamento-clies-lvs.pdf'),
('REGLAMENTOS', 'REGLAMENTO GENERAL DE DOCENTES Y JEFES DE PRÁCTICA', 'Res. N°289-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-289-2017-UAC-reglamento-docentes-jefes-practica.pdf'),
('REGLAMENTOS', 'Modifican el articulo 61° del Reglamento General de Docentes y Jefes de Práctica de la Universidad Andina del Cusco.', 'Res. N°284-2019/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2019/R_CU-284-2019-UAC-modificacion-reglamento-289CU2017.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE VOLUNTARIADO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°242-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-242-2017-UAC-reglamento-voluntariado-uac.pdf'),
('REGLAMENTOS', 'Modifican el literal c) del articulo 1° y literal d) del articulo 29° del Reglamento de Voluntariado de la Universidad Andina del Cusco.', 'Res. N°414-2017/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-414-2017-UAC-modificacion-reglamento-voluntariado.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE CERTIFICACIÓN INTERMEDIA DE LA ESCUELA PROFESIONAL DE INGENIERÍA DE SISTEMAS DE LA FACULTAD DE INGENIERÍA Y ARQUITECTURA', 'Res. N°658-2021/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_CU-658-2021-UAC-reglamento-certificacion-intermedia-is.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL TRIBUNAL DE HONOR DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°072-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-072-2017-UAC-reglamento-tribunal-honor.pdf'),
('REGLAMENTOS', 'REGLAMENTO ESPECÍFICO DEL PROGRAMA DE SEGUNDA ESPECIALIDAD DE INTERVENCIÓN EN CASOS DE VIOLENCIA FAMILIAR', 'Res. N°067-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-067-2017-UAC-reglamento-SE-intervencion-violencia-familiar.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE LOS DOCENTES EXTRAORDINARIOS DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°050-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-050-2017-UAC-reglamento-docentes-extraordinarios.pdf'),
('REGLAMENTOS', 'Modificar parcialmente la resolución N° 050-CU-2017', 'Res. N° 277-2025/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_CU-277-2025-UAC-modifican-Res050cu2017.pdf'),
('REGLAMENTOS', 'REGLAMENTO ESPECÍFICO DEL PROGRAMA DE SEGUNDA ESPECIALIDAD DE LA ESCUELA PROFESIONAL DE ESTOMATOLOGÍA', 'Res. N°448-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-448-2017-UAC-reglamento-SE-estomatologia.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE OTORGAMIENTO DE AUSPICIO INSTITUCIONAL DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°489-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-489-2016-UAC-reglamento-otorgar-auspicio.pdf'),
('REGLAMENTOS', 'REGLAMENTO GENERAL DE LA ESCUELA DE POSGRADO', 'Res. N°665-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-665-2016-UAC-reglamento-general-epg.pdf'),
('REGLAMENTOS', 'REGLAMENTO GENERAL DE LAS DISCIPLINAS DEPORTIVAS DE LA UNIVERSIDAD ANDINA DEL CUSCO Y FILIALES', 'Res. N°664-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-664-2016-UAC-reglamento-disciplinas-deportivas.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE LABORATORIOS DE INGENIERÍA CIVIL DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°384-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-384-2016-UAC-reglamento-laboratorios-ic.pdf'),
('REGLAMENTOS', 'REGLAMENTO GENERAL DE ESTUDIANTES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°291-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-291-2017-UAC-reglamento-general-estudiantes.pdf'),
('REGLAMENTOS', 'Modifican artículo 30° y 31° del Reglamento General de Estudiantes de la Universidad Andina del Cusco.', 'Res. N°260-2018/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-260-2018-UAC-modifican-articulo.pdf'),
('REGLAMENTOS', 'Modifican literal h) del artículo 46° del Reglamento General de Estudiantes de la Universidad Andina del Cusco.', 'Res. N°620-2018/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-620-2018-UAC-modifican-literal.pdf'),
('REGLAMENTOS', 'Rectifican el error material contenido en la Resolución N° 620-CU-2018-UAC', 'Res. N°641-2018/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-641-2018-UAC-rectifican-620CU2018.pdf'),
('REGLAMENTOS', 'Modifican el artículo 43° del Reglamento General de Estudiantes de la Universidad Andina del Cusco.', 'Res. N°398-2020/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2020/R_CU-398-2020-UAC-modifican-art43-291CU2017.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE MÉRITOS ACADÉMICOS DE LOS ESTUDIANTES Y EGRESADOS DE LA UNIVERSIDAD ANDINA DEL CUSCO.', 'Res. N°190-2023/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-190-2023-UAC-meritos-academicos.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE EDITORIAL UNIVERSITARIA.', 'Res. N°602-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-602-2016-UAC-editorial-universitaria.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL SISTEMA INSTITUCIONAL DE TUTORÍA Y ATENCIÓN PSICOPEDAGÓGICA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°500-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-500-2016-UAC-sistema-tutoria-psicopedagogica.pdf'),
('REGLAMENTOS', 'REGLAMENTO INTERNO DEL CONSEJO DE FACULTAD DE CIENCIAS ECONÓMICAS, ADMINISTRATIVAS Y CONTABLES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°507-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-507-2016-UAC-consejo-facultad-ceac.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL USO DE EQUIPOS DE COMPUTO, PROYECTORES INTERACTIVOS Y LABORATORIOS DE LA FACULTAD DE CIENCIAS ECONÓMICAS, ADMINISTRATIVAS Y CONTABLES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°508-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-508-2016-UAC-uso-equipos-computo-ceac.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE LA ESCUELA DE ESTUDIOS DE FORMACIÓN GENERAL DE LA FACULTAD DE CIENCIAS Y HUMANIDADES', 'Res. N°581-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-581-2016-UAC-estudios-formacion-general.pdf'),
('REGLAMENTOS', 'Modifican artículo 15° del Reglamento de la Escuela de Estudios de Formación General de la Facultad de Ciencias y Humanidades de la Universidad Andina del Cusco.', 'Res. N°428-2017/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-428-2017-UAC-modificar-reglamento-estudios-formacion-general.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE ATENCIÓN A POSTULANTES Y ESTUDIANTES UNIVERSITARIOS CON DISCAPACIDAD DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°504-2014/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/documentos/normativos/R_CU-504-2014-UAC-reglamento-estudiantes-discapacidad.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE PROGRAMA DE PRODUCTIVIDAD, ESTÍMULOS E INCENTIVOS PARA EL PERSONAL ADMINISTRATIVO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°510-2014/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/documentos/normativos/R_CU-510-2014-UAC-reglamento-incentivos-administrativos.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE PROGRAMA DE ESTÍMULOS E INCENTIVOS PARA ESTUDIANTES UNIVERSITARIOS DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°240-2014/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-240-2014-UAC-reglamento-incentivos-estudiantes.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE PROCEDIMIENTOS PARA INVESTIGACIÓN', 'Res. N°135-2015/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/documentos/normativos/R_CU-135-2015-UAC-procedimientos-investigacion.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE USO DE LOCALES E INSTALACIONES DE LA UNIVERSIDAD ANDINA DEL CUSCO.', 'Res. N°205-2012/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/documentos/normativos/R_CU-205-2012-UAC.pdf'),
('REGLAMENTOS', 'REGLAMENTO GENERAL DE ELECCIONES UNIVERSITARIAS DE LA UNIVERSIDAD ANDINA DEL CUSCO, PARA ELEGIR A LOS DELEGADOS REPRESENTANTES DE LOS PROFESORES, ESTUDIANTES Y GRADUADOS ANTE LOS ÓRGANOS DE GOBIERNO.', 'Res. N°051-2013/SG-UAC', 0, 'https://www.uandina.edu.pe/descargas/documentos/normativos/R_CU-051-2013-SG-UAC.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE GESTIÓN Y SUSCRIPCIÓN DE CONVENIOS INTERINSTITUCIONALES PARA LA UAC.', 'Res. N°041-2014/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/documentos/normativos/R_CU-041-2014-UAC-reglamento-para-convenios.pdf'),
('REGLAMENTOS', 'REGLAMENTO MARCO DE CENTROS DE PRODUCCIÓN Y PRESTACIÓN DE SERVICIOS DE LA UAC.', 'Res. N°042-2014/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/documentos/normativos/R_CU-042-2014-UAC-reglamento-centros-produccion-servicios.pdf'),
('REGLAMENTOS', 'REGLAMENTO DEL PROGRAMA DE PROFESIONALIZACIÓN ACADÉMICA EN TURISMO.', NULL, 0, 'https://www.uandina.edu.pe/descargas/documentos/normativos/R_CU-063-2014-UAC-reglamento-programa-profesionalizacion-turismo.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE TITULACIÓN BAJO LA MODALIDAD DE TALLERES DE TESIS (PRO TESIS) DE LA CARRERA PROFESIONAL DE EDUCACIÓN.', NULL, 0, 'https://www.uandina.edu.pe/descargas/documentos/normativos/R_CU-036-2014-UAC-reglamento-titulacion-protesis-educacion.pdf'),
('REGLAMENTOS', 'REGLAMENTO DE LA ASAMBLEA UNIVERSITARIA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°010-2014/AU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-010-2014-UAC-reglamento-asamble-universitaria.pdf'),
('REGLAMENTOS', 'REGLAMENTO INTERNO DEL CONSEJO UNIVERSITARIO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°478-2014/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-478-2014-UAC-reglamento-consejo-universitario.pdf');

-- === EJERCICIO PRE PROFESIONAL ===
INSERT INTO reglamentos (seccion, titulo, resolucion, es_subitem, enlace) VALUES
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO MARCO DE EJERCICIO PRE PROFESIONAL Y PRÁCTICAS PROFESIONALES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°653-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-653-2024-UAC-ejercicio-pre-profesional.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO ESPECÍFICO DEL EJERCICIO PRE PROFESIONAL DE LA ESCUELA PROFESIONAL DE DERECHO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°506-2023/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-506-2023-UAC-reglamento-pre-profesional-derecho.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO DEL EJERCICIO PRE PROFESIONAL DE LA FACULTAD DE INGENIERÍA Y ARQUITECTURA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°469-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-469-2022-UAC-ejercicio-preprofesional-fia.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO DEL EJERCICIO PRE PROFESIONAL DE LA ESCUELA PROFESIONAL DE TURISMO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°034-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-034-2022-UAC-reglamento-pre-profesional-turismo.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO DEL EJERCICIO PRE PROFESIONAL DE LA ESCUELA PROFESIONAL DE OBSTETRICIA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°058-2023/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-058-2023-UAC-ejercicio-pre-profesional-obstericia.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO DEL EJERCICIO PRE PROFESIONAL – INTERNADO DE LA ESCUELA PROFESIONAL DE PSICOLOGÍA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°057-2023/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-057-2023-UAC-ejercicio-pre-profesional-psicologia.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO DEL EJERCICIO PRE PROFESIONAL DE LA ESCUELA PROFESIONAL DE EDUCACIÓN DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°035-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-035-2022-UAC-reglamento-pre-profesional-educacion.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO DE PRÁCTICAS PRE PROFESIONALES DE LA ESCUELA PROFESIONAL DE OBSTETRICIA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°244-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-244-reglamento-ppp-obstetricia.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO DE PRÁCTICAS PRE PROFESIONALES DEL INTERNADO DE LA ESCUELA PROFESIONAL DE PSICOLOGÍA', 'Res. N°112-2017/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-112-2017-UAC-reglamento-ppp-internado-psi.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO DE PRÁCTICAS PRE PROFESIONALES Y PROFESIONALES DE LAS ESCUELAS PROFESIONALES DE ECONOMÍA, ADMINISTRACIÓN Y CONTABILIDAD DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°676-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-676-reglamento-ppp-ceac.pdf'),
('EJERCICIO PRE PROFESIONAL', 'REGLAMENTO ESPECÍFICO DE PRÁCTICAS PRE-PROFESIONALES Y PROFESIONALES DE LA ESCUELA PROFESIONAL DE DERECHO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°530-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/R_CU-530-2016-UAC-practicas-der.pdf');

-- === INTERNADO ===
INSERT INTO reglamentos (seccion, titulo, resolucion, es_subitem, enlace) VALUES
('INTERNADO', 'REGLAMENTO de INTERNADO DE LA ESCUELA PROFESIONAL DE ESTOMATOLOGÍA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°060-2023/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-060-2023-UAC-internado-estomatologia.pdf'),
('INTERNADO', 'REGLAMENTO DE INTERNADO CLÍNICO ESCUELA PROFESIONAL DE TECNOLOGÍA MÉDICA TERAPIA FÍSICA Y REHABILITACIÓN DE LA FACULTAD DE CIENCIAS DE LA SALUD DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°330-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-330-2022-UAC-reglamento-internado-clinico-tecnologia-medica.pdf');

-- === GRADOS Y TÍTULOS ===
INSERT INTO reglamentos (seccion, titulo, resolucion, es_subitem, enlace) VALUES
('GRADOS Y TÍTULOS', 'REGLAMENTO ESPECÍFICO PARA OBTENER EL GRADO ACADÉMICO DE BACHILLER Y EL TÍTULO PROFESIONAL EN LA FACULTAD DE INGENIERÍA Y ARQUITECTURA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°529-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/reglamentos/2025/R_CU-529-2025-UAC-grado-titulo-fia.pdf'),
('GRADOS Y TÍTULOS', 'REGLAMENTO ESPECÍFICO PARA LA OBTENCIÓN DEL GRADO ACADÉMICO DE BACHILLER Y EL TÍTULO PROFESIONAL DE ABOGADO A NOMBRE DE LA NACIÓN, EN LA FACULTAD DE DERECHO Y CIENCIA POLÍTICA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°508-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/reglamentos/2025/R_CU-508-2025-UAC-reglamento-especifico-grados-titulos-derecho.pdf'),
('GRADOS Y TÍTULOS', 'REGLAMENTO ESPECÍFICO DE GRADOS Y TÍTULOS PARA OBTENER EL GRADO ACADÉMICO DE BACHILLER Y EL TÍTULO PROFESIONAL DE LICENCIADO EN TURISMO/EDUCACIÓN LA FACULTAD DE CIENCIAS Y HUMANIDADES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°312-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_312-2025-CU-UAC-reglamento-especifico-turismo-educacion.pdf'),
('GRADOS Y TÍTULOS', 'REGLAMENTO ESPECÍFICO PARA OBTENER EL GRADO ACADÉMICO DE BACHILLER Y EL TÍTULO PROFESIONAL DE LA FACULTAD DE CIENCIAS ECONÓMICAS, ADMINISTRATIVAS Y CONTABLES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°289-2025/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2025/R_289-2025-CU-UAC-reglamento-especifico-ceac.pdf'),
('GRADOS Y TÍTULOS', 'REGLAMENTO ESPECÍFICO PARA OBTENER EL GRADO ACADÉMICO DE BACHILLER Y EL TÍTULO PROFESIONAL EN LA FACULTAD DE CIENCIAS DE LA SALUD DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°513-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_513-2024-CU-UAC-reglamento-especifico-facsa.pdf'),
('GRADOS Y TÍTULOS', 'REGLAMENTO MARCO PARA OBTENER EL GRADO ACADÉMICO DE BACHILLER Y EL TÍTULO PROFESIONAL EN LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°256-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-256-2024-UAC-reglamento-marco-grados-titulos.pdf'),
('GRADOS Y TÍTULOS', 'REGLAMENTO ESPECÍFICO DE GRADOS Y TÍTULOS DE LA FACULTAD DE CIENCIAS Y HUMANIDADES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°374-2021/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_CU-374-2021-UAC-grados-titulos-fcsh.pdf'),
('GRADOS Y TÍTULOS', 'Modifican artículos 33° y 58° del Reglamento Específico de grados y títulos de la Facultad de Ciencias y Humanidades en mérito al Oficio N°0831-2022/INDECOPI-SRB', 'Res. N° 411-2022/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-411-2022-UAC-modificacion-reglamento-fch-150822.pdf'),
('GRADOS Y TÍTULOS', 'REGLAMENTO ESPECÍFICO DE GRADOS Y TÍTULOS DE LA FACULTAD DE CIENCIAS ECONÓMICAS, ADMINISTRATIVAS Y CONTABLES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°414-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-414-2022-UAC-grados-titulos-fceac.pdf'),
('GRADOS Y TÍTULOS', 'REGLAMENTO ACTUALIZADO PARA EL OTORGAMIENTO DE DUPLICADOS DE DIPLOMAS DE GRADOS Y TÍTULOS EMITIDOS POR LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°116-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-116-2023-UAC-duplicados-diplomas-gyt.pdf');

-- === POSGRADO ===
INSERT INTO reglamentos (seccion, titulo, resolucion, es_subitem, enlace) VALUES
('POSGRADO', 'REGLAMENTO DE HOMOLOGACIONES Y CONVALIDACIONES DE LA ESCUELA DE POSGRADO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 484-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-484-2022-UAC-reglamento-homologaciones-convalidaciones.pdf'),
('POSGRADO', 'Modifican los artículos 26 y 29 del reglamento de homologaciones y convalidaciones de la Escuela de Posgrado de la Universidad Andina del Cusco', 'Res. N° 603-2024/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-603-2024-UAC-modificacion-reglamento-484CU22.pdf');

-- === SEGUNDAS ESPECIALIDADES ===
INSERT INTO reglamentos (seccion, titulo, resolucion, es_subitem, enlace) VALUES
('SEGUNDAS ESPECIALIDADES', 'REGLAMENTO ESPECÍFICO DE LOS PROGRAMAS DE LA SEGUNDA ESPECIALIDAD DE LA ESCUELA PROFESIONAL DE ESTOMATOLOGÍA DE LA UNIVERSIDAD ANDINA DEL CUSCO Y ANEXOS', 'Res. N° 587-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-587-2024-UAC-reglamento-especifico-se-estomatologia.pdf'),
('SEGUNDAS ESPECIALIDADES', 'REGLAMENTO ESPECÍFICO DE LOS PROGRAMAS DE LA SEGUNDA ESPECIALIDAD DE LA ESCUELA PROFESIONAL DE OBSTETRICIA DE LA UNIVERSIDAD ANDINA DEL CUSCO Y ANEXOS', 'Res. N° 588-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-588-2024-UAC-reglamento-especifico-se-obstetricia.pdf'),
('SEGUNDAS ESPECIALIDADES', 'REGLAMENTO ESPECÍFICO DE LOS PROGRAMAS DE LA SEGUNDA ESPECIALIDAD DE LA ESCUELA PROFESIONAL DE ENFERMERÍA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 589-2024/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-589-2024-UAC-reglamento-especifico-se-enfemeria.pdf'),
('SEGUNDAS ESPECIALIDADES', 'REGLAMENTO MARCO DE SEGUNDA ESPECIALIDAD DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N°310-2022/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2022/R_CU-310-2022-UAC-reglamento-segunda-especialidad.pdf'),
('SEGUNDAS ESPECIALIDADES', 'Incorporan artículo en el capítulo V: de la matrícula y modifican correlación de artículos en el citado reglamento', 'Res. N° 213-2023/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2023/R_CU-213-2023-UAC-modificacion-reglamento-310CU22.pdf');

-- === DEFENSORIA UNIVERSITARIA ===
INSERT INTO reglamentos (seccion, titulo, resolucion, es_subitem, enlace) VALUES
('DEFENSORIA UNIVERSITARIA', 'REGLAMENTO DE LA DEFENSORIA UNIVERSITARIA DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 152-2016/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2016/R_CU-152-2016-UAC-reglamento-defensoria-universitaria.pdf'),
('DEFENSORIA UNIVERSITARIA', 'Modifican los artículos 17 y 21 del Reglamento de la Defensoría Universitaria de la Universidad Andina del Cusco', 'Res. N° 167-2024/CU-UAC', 1, 'https://www.uandina.edu.pe/descargas/transparencia/2024/R_CU-167-2024-UAC-modificacion-reglamento-152CU16.pdf'),
('DEFENSORIA UNIVERSITARIA', 'REGLAMENTO SOBRE HOSTIGAMIENTO SEXUAL PARA ESTUDIANTES Y DOCENTES DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 690-2021/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2021/R_CU-690-2021-UAC-reglamento-hostigamiento.pdf'),
('DEFENSORIA UNIVERSITARIA', 'REGLAMENTO SOBRE HOSTIGAMIENTO SEXUAL PARA EL PERSONAL ADMINISTRATIVO DE LA UNIVERSIDAD ANDINA DEL CUSCO', 'Res. N° 014-2020/CU-UAC', 0, 'https://www.uandina.edu.pe/descargas/transparencia/2020/R_CU-014-2020-UAC-reglamento-hostigamiento-adm.pdf');